# Important Notes:
# Every field you add must be added to build-logic/src/main/kotlin/multiloader-common.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Project
version=1.0.0
group=com.wfphantom
java_version=21

# Common
minecraft_version=1.21.1
mod_name=STFU Social
mod_id=stfusocial
# Review your options at https://choosealicense.com/.
license=MIT
description=Microsoft PLEASE STOP
minecraft_version_range=[1.21.1]
## This is the version of minecraft that the 'common' project uses. You can find a list of all versions here
## see https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# Optional
mod_authors=WFPhantom
credits=
issue_tracker=https://github.com/WFPhantom/stfusocial/issues
homepage=https://github.com/WFPhantom/stfusocial
# common/src/main/resources/assets/examplemod/
logo=aseets/stfusocial/logo.png

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.1.255
# ModDevGradle, see https://projects.neoforged.net/neoforged/moddevgradle for new versions
mdg_version=2.0.148
# Optional, see https://docs.neoforged.net/docs/misc/updatechecker/
update_json_url=https://change.me.example.invalid/updates.json