# Important Notes:
# Every field you add must be added to build-logic/src/main/kotlin/multiloader-common.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Project
version=1.0.0
group=com.example
java_version=25

# Common
minecraft_version=26.1.2
mod_name=ExampleMod
mod_id=examplemod
# Review your options at https://choosealicense.com/.
license=CC0-1.0
description=The description of your mod. \nAccepts multilines.
minecraft_version_range=[26.1.2, 26.2)
## This is the version of minecraft that the 'common' project uses. You can find a list of all versions here
## see https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
# Optional
mod_authors=Example
credits=
issue_tracker=https://change.me.to.your.issue.tracker.example.invalid/
homepage=https://change.me.to.your.mods.homepage.example.invalid/
# common/src/main/resources/assets/examplemod/
logo=aseets/examplemod/examplemod.png

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.82
# ModDevGradle, see https://projects.neoforged.net/neoforged/moddevgradle for new versions
mdg_version=2.0.142
# Optional, see https://docs.neoforged.net/docs/misc/updatechecker/
update_json_url=https://change.me.example.invalid/updates.json

# Fabric Dependencies (optional)
fabric_api_version=0.155.2+26.1.2
#fabric_kotlin_version=1.13.13+kotlin.2.4.10

# Neo Dependencies (optional)
#neo_kotlin_version=
